local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.3
  rolling_window: true
  width: 3
  height: 3
  origin_x: 0
  origin_y: 0
  resolution: 0.1
  inflation_radius: 0.6
  plugins:
      - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
